name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case for this feature. How would you use it? What problem does it solve?
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
      
  - type: dropdown
    id: contribution
    attributes:
      label: Are you willing to contribute?
      description: Would you be willing to submit a PR with this feature?
      options:
        - "Yes, I'd like to contribute"
        - "Yes, but I'd need guidance"
        - "No, but I'm available for testing"
        - "No"
    validations:
      required: true
      
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: |
        If applicable, provide code examples or mockups of how this feature would work.
        This will be automatically formatted as code.
      render: python
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the feature request here.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/yourusername/md2pdf/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true